apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "name" is the name of the ClusterRole
  name: cluster-admin
  namespace: kafka-pipeline
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
