apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kafkastreamingdata
  name: pod-manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]  # Allows executing commands in pods
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]  # Allows access to pod logs
