apiVersion: v1
kind: PersistentVolume
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-data
  name: kafka-keystore-volume
spec:
  #storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Mi
  hostPath:
    path: "app/kafka-keystore"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-claim-data
  name: kafka-keystore-volume
  namespace: kafka-pipeline
spec:
  #storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
status: {}
