apiVersion: v1
kind: PersistentVolume
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-data
  name: app-merge-data
spec:
  #storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "app/app-merge-data"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-claim-data
  name: app-merge-data
  namespace: "kafkastreamingdata"
spec:
  #storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
