apiVersion: v1
kind: PersistentVolume
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-data
  name: merged-data
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "app/merged-clstr-data"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.service: producer-claim-data
  name: merged-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
