apiVersion: v1
kind: PersistentVolume
metadata:
  name: producer-data
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: "app/producer-data"
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: producer-data
  namespace: "kafkastreamingdata"
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
