apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-configmap
data:
  ############# KAFKA PROPERTIES #############################
  KAFKA_TOPIC_COUNT: "10"
  #KAFKA_SERVER_URI_PRODUCER: "kafka-0.kafka-headless.kafkastreamingdata.svc.cluster.local:9092"
  #KAFKA_SERVER_URI_CONSUMER: "kafka.kafkastreamingdata.svc.cluster.local:9092"
  KAFKA_INSTALL_PATH: "/kafka/bin/"

  ############# PRODUCER PROPERTIES #############################
  PRODUCER_COUNT: "1"
  PRODUCER_TOPIC_COUNT: "10"
  PRODUCER_INPUT_PATH: 'request-producer-data'
  PRODUCER_POD_COUNT: "1"
  WAITE_TIME: "10"
  BATCH_SIZE: "100"
  TOPIC_TITLE: "ukrain"


  ############# CONSUMER PROPERTIES #############################
  auto_offset_reset: "earliest"
  group_id: "StreamData"
  max_in_flight_requests_per_connection: "1"
  enable_auto_commit: "true"
  auto_commit_interval_ms: "5000"
  enable.idempotence: "true"
  CONSUMER_POD_COUNT: "1"
  CONSUMER_COUNT: "1"
  CONSUMER_WINDOW_COUNT: "2"

  ##### APPLICATION POD VARIABLES ##########################
  APPLICATION_WAIT_TIME: "60"
  APPLICATION_COUNT: "1"



  ############### ZIKA VARIABLES ##############################
  ZIKA_DATA_ADDRESS: "./data/zika_data_only_hashtags.csv"
  RARELIST_DATA_ADDRESS: "./data/rarelist.pkl"
  h5py_path: "consumer-app-data/zika"

  ############## PASCAL-G VARIABLES ########################
  Column_Range: "500000"
  Row_Range: "500000"
  fps: "[ ]"
  sim1: "dotsim"
  sim2: "dotsim"
  thr1: "0.3"
  thr2: "0.6"
  outliers_action: "remove"
  thmls: "[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]"
  thcls: "[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]"
  edge_list_path: "./data/network_data/edges"
  node_edges_path: "./data/network_data/node_edges"
  log_path_findCl: "./logs/pascal-g/findProbCl"
  log_path_mergeCl: "./logs/pascal-g/mergeProbFi"
  csr_matrix_path: "./data/csr_matrix"
  Vacc_H5path: "consumer-app-data/vacc"
  shared_H5path: "consumer-app-data/vacc/2023-06-06/17-10-24"
  local_clstr_path: "./app-merge-data"
  Ukraine_H5path: "./consumer-app-data/ukraine"
  H5PY_PATH: "./consumer-app-data"

  ##### REQUEST POD VARIABLES ########################
  REQUEST_COUNT: "1"
  RequestURL: 'http://127.0.0.1:8080/'
  RequestInputPath: "../../data/simulator"
  RequestOutputPath: "./request-producer-data"
  StartDate : '2022-8-01-00'
  EndDate : '2022-8-01-02'
  RequestWindow : 'hour'
  Wait : '10'
  RqstPodMntPath: "request-data"
  RqstPodSharedPath: "request-producer-data"

  ############# MERGE PODS VARIABLES ###############

  MERGE_COUNT: "1"
  MERGE_WAIT_TIME: "600"
  MERGE_WAIT_THRESHOLD: "20"
  merge_path: "./merged-clstr-data"