apiVersion: apps/v1
kind: StatefulSet      
metadata:
  name: "cons-seizure-sts"
  namespace: kafkastreamingdata
  labels: 
    app: "cons-seizure-sts"
    serviceSelector: "cons-seizure-sts"
spec:
  selector: 
    matchLabels: 
      app: "cons-seizure-sts"
  serviceName: "cons-seizure-sts-svc"
  replicas: 1 
  podManagementPolicy: Parallel
  minReadySeconds: 10
  template:
    metadata: 
      labels:
        app: "cons-seizure-sts"
    spec: 
      containers:
        - name: "cons-seizure-sts"
          image: sjafari2/seizureapplication:latest
          ports:
          - containerPort: 9094
            name: "app-port"
          command: ["/bin/bash", "-c"]
          args: 
            - |
              source runCons.sh  
              sleep infinity
          resources: 
            limits:
              memory: "100Gi"
              cpu: "8"
            requests:
              memory: "100Gi"
              cpu: "8"
          volumeMounts:
          - mountPath: app/cons-seizure-app/
            name: cons-seizure-app
            #          - mountPath: app/app-merge-data
           #            name: app-merge-data
      volumes:
       - name: cons-seizure-app
         persistentVolumeClaim:
           claimName: cons-seizure-app
           #        - name: app-merge-data
              #          persistentVolumeClaim:
              #            claimName: app-merge-data
              #            
              #      affinity:
              #        podAntiAffinity:
              #          requiredDuringSchedulingIgnoredDuringExecution:
              #          - labelSelector:
              #              matchExpressions:
              #              - key: app
              #                operator: In
              #                values:
              #                - cons-seizure-sts
              #                - merge-sts
              #                - prod-sts
              #                - kafka
              #                - kafka-zookeeper
              #            topologyKey: "kubernetes.io/hostname"

            #        terminationGracePeriodSeconds: 10
      #  securityContext:
      #    runAsUser: 1000
      #    runAsGroup: 3000
      #    fsGroup: 2000
      #    fsGroupChangePolicy: "Always"
      #    restartPolicy: OnFailure
#  volumeClaimTemplates:
#  - metadata:
#      name: "cons-seizureumer-app-data"
#      creationTimestamp: null
#      labels:
#        io.kompose.service: "cons-seizureumer-app-data"
#        #      name: kafka-claim-data
#    spec:
#      storageClassName: rook-cephfs-central
#      accessModes:
#        - ReadWriteMany
#      resources:
#        requests:
#          storage: 100Gi
#
