apiVersion: apps/v1
kind: StatefulSet      
metadata:
  name: "cons-sts"
  namespace: kafkastreamingdata
  labels: 
    app: "cons-sts"
    serviceSelector: "cons-sts"
spec:
  selector: 
    matchLabels: 
      app: "cons-sts"
  serviceName: "cons-sts-svc"
  replicas: 2
  podManagementPolicy: Parallel
  minReadySeconds: 10
  template:
    metadata: 
      labels:
        app: "cons-sts"
    spec: 
      containers:
        - name: "consumer-sts"
          image: sjafari2/kafkaconsumer:8-8-2023
          env:
          - name: POD_ORDINAL
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              chmod +x runconsumer.sh  
              sleep infinity
          ports:
          - containerPort: 9092
            name: "consumer-port"
          - containerPort: 9093
            name: "exporter-port"       
          resources: 
            limits:
              memory: "100Gi"
              cpu: "4"
            requests:
              memory: "100Gi"
              cpu: "4"
          volumeMounts:
          - mountPath: app/consumer-app
            name: consumer-app
           #      restartPolicy: OnFailure           
        - name: "application-sts"
          image: sjafari2/kafkapplication:8-8-2023
          ports:
          - containerPort: 9094
            name: "app-port"
          command: ["/bin/bash", "-c"]
          args: 
            - |
              rm -rf ./app-merge-data/*
              rm -rf ./logs/*
              pod_name=$(hostname)
              ordinal=$(echo "$pod_name" | rev | cut -d '-' -f 1 | rev)
              echo "Pod ordinal value is: $ordinal"
              chmod +x runapplication.sh  
              sleep infinity
          resources: 
            limits:
              memory: "100Gi"
              cpu: "4"
            requests:
              memory: "100Gi"
              cpu: "4"
          volumeMounts:
          - mountPath: app/consumer-app
            name: consumer-app
          - mountPath: app/app-merge-data
            name: app-merge-data
      volumes:
        - name: consumer-app
          persistentVolumeClaim:
            claimName: consumer-app
        - name: app-merge-data
          persistentVolumeClaim:
            claimName: app-merge-data
            
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cons-sts
                - merge-sts
                - prod-sts
                - kafka
                - kafka-zookeeper
            topologyKey: "kubernetes.io/hostname"

            #        terminationGracePeriodSeconds: 10
      #  securityContext:
      #    runAsUser: 1000
      #    runAsGroup: 3000
      #    fsGroup: 2000
      #    fsGroupChangePolicy: "Always"
      #    restartPolicy: OnFailure
#  volumeClaimTemplates:
#  - metadata:
#      name: "consumer-app-data"
#      creationTimestamp: null
#      labels:
#        io.kompose.service: "consumer-app-data"
#        #      name: kafka-claim-data
#    spec:
#      storageClassName: rook-cephfs-central
#      accessModes:
#        - ReadWriteMany
#      resources:
#        requests:
#          storage: 100Gi
#
