#!/bin/bash

# Define the namespace
namespace="kafkastreamingdata"

# Get the list of StatefulSets in the specified namespace
statefulsets=$(kubectl get statefulsets -n "$namespace" -o custom-columns=":metadata.name" --no-headers)

# Loop through each StatefulSet
for statefulset in $statefulsets; do
  # Get the log paths from the StatefulSet configuration
  log_paths=$(kubectl get statefulset "$statefulset" -n "$namespace" -o jsonpath='{.spec.template.spec.containers[*].env[?(@.name=="LOG_PATH")].value}')

  # Loop through the log paths
  for log_path in $log_paths; do
    # Get the list of pods generated by the StatefulSet
    pod_list=$(kubectl get pods -n "$namespace" -l "statefulset.kubernetes.io/pod-name" | grep "$statefulset" | awk '{print $1}')

    # Loop through each pod
    for pod in $pod_list; do
      # Get the list of containers in the pod
      container_list=$(kubectl get pod "$pod" -n "$namespace" -o jsonpath="{.spec.containers[*].name}")

      # Loop through each container
      for container in $container_list; do
        # Execute the removal command within the container for the specified log path
        kubectl exec -it "$pod" -n "$namespace" -c "$container" -- /bin/sh -c "rm -f $log_path"
      done
    done
  done
done

